
const apiKeys = [
    { key: "6dN85BBakq", user: "dknapp" },
    { key: "SpOVmYMm9F", user: "eumobi" },
    { key: "fyogR8VWad", user: "" },
    { key: "qFKzGHzpdy", user: "" },
    { key: "Z0Vrgc71JC", user: "" },
    { key: "5gzSlNO65I", user: "" },
    { key: "9X5dvhew26", user: "" },
    { key: "NybZMoDN2Q", user: "" },
    { key: "fip5EZROPo", user: "" },
    { key: "d1wMzvGS5X", user: "" },
    { key: "OywgFPDjYe", user: "" },
    { key: "3WwAxlCDAf", user: "" },
    { key: "MSW7hQ0rTo", user: "" },
    { key: "8VWsGoY5aC", user: "" },
    { key: "1Vyl12pXDC", user: "" },
    { key: "SJZ4X84IrN", user: "" },
    { key: "GgG76wPrrU", user: "" },
    { key: "7uw5XfIde8", user: "" },
    { key: "SDkKHdOO1O", user: "" },
    { key: "hMJ3dqVGMw", user: "" },
    { key: "gEQik8rIWY", user: "" },
    { key: "B2EgVtpZwh", user: "" },
    { key: "ekvfkaJyti", user: "" },
    { key: "L1XiKVnr9Z", user: "" },
    { key: "dMc78DDTSC", user: "" },
    { key: "X3CUz8XTSd", user: "" },
    { key: "rvZrzfBjEZ", user: "" },
    { key: "u0aetKloIt", user: "" },
    { key: "qm6BUReGvn", user: "" },
    { key: "PGGIIY9mCZ", user: "" },
    { key: "testing", user: "testing", rateLimit: { perMinute: 120, timeBetween: 100 } }
];

module.exports = apiKeys;
